"""
build_db.py - Load the cleaned data into a SQLite database.

WHY A DATABASE AND NOT JUST CSVs
--------------------------------
Three reasons, in order of how much they actually matter here:

1. The API needs to answer "give me every turn on 14 March" in milliseconds.
   Reading a 75,000-row CSV and filtering it on every web request works, but
   it means the whole file sits in memory and every request pays for a full
   scan. An indexed SQL query does not.

2. Model outputs need somewhere to live. Gate assignments, cost breakdowns and
   saved scenarios are all results we want to write back and read later. A pile
   of output CSVs with ad-hoc filenames becomes unmanageable within a week.

3. SQL is the interface everything else speaks. Nothing downstream needs to
   know how the turns were built - it just queries a table.

SQLite specifically because it is a single file, needs no server, and ships
with Python. If this ever outgrows one machine, the same schema moves to
PostgreSQL with almost no changes.
"""

import sqlite3

import pandas as pd

from alto import build_turns, config, gates as gates_module


# The schema is written out in full rather than generated by an ORM, so that
# anyone reading this file can see exactly what the database contains.
SCHEMA = """
DROP TABLE IF EXISTS turns;
CREATE TABLE turns (
    turn_id                     INTEGER PRIMARY KEY,
    tail_number                 TEXT    NOT NULL,
    turn_type                   TEXT    NOT NULL,   -- turnaround / arrival_only / departure_only
    arrival_date                TEXT    NOT NULL,   -- YYYY-MM-DD, the day it landed
    arrival_flight              INTEGER,
    departure_flight            INTEGER,
    arrival_origin              TEXT,               -- where it came from
    departure_dest              TEXT,               -- where it goes next
    arrival_minute              INTEGER NOT NULL,   -- minutes since 1 Jan 00:00
    departure_minute            INTEGER NOT NULL,
    ground_minutes              INTEGER NOT NULL,
    scheduled_arrival_minute    INTEGER,
    scheduled_departure_minute  INTEGER,
    arrival_delay_minutes       REAL,
    departure_delay_minutes     REAL
);
CREATE INDEX idx_turns_date ON turns(arrival_date);
CREATE INDEX idx_turns_tail ON turns(tail_number, arrival_minute);

DROP TABLE IF EXISTS gate_blocks;
CREATE TABLE gate_blocks (
    block_id        INTEGER PRIMARY KEY,
    turn_id         INTEGER NOT NULL,
    tail_number     TEXT    NOT NULL,
    arrival_date    TEXT    NOT NULL,
    start_minute    INTEGER NOT NULL,
    end_minute      INTEGER NOT NULL,
    block_type      TEXT    NOT NULL,   -- 'full', 'arrival', or 'departure'
    FOREIGN KEY (turn_id) REFERENCES turns(turn_id)
);
CREATE INDEX idx_blocks_date ON gate_blocks(arrival_date);

DROP TABLE IF EXISTS gates;
CREATE TABLE gates (
    gate_id     TEXT PRIMARY KEY,       -- 'C12', 'N4', 'D7'
    concourse   TEXT NOT NULL,
    size        TEXT NOT NULL,
    walk_cost   REAL NOT NULL
);

DROP TABLE IF EXISTS assignments;
CREATE TABLE assignments (
    assignment_id   INTEGER PRIMARY KEY,
    scenario_id     TEXT NOT NULL,      -- 'baseline' or a scenario hash
    block_id        INTEGER NOT NULL,
    gate_id         TEXT NOT NULL,
    FOREIGN KEY (block_id) REFERENCES gate_blocks(block_id),
    FOREIGN KEY (gate_id)  REFERENCES gates(gate_id)
);
CREATE INDEX idx_assign_scenario ON assignments(scenario_id);

DROP TABLE IF EXISTS build_log;
CREATE TABLE build_log (
    key     TEXT PRIMARY KEY,
    value   TEXT
);
"""


def create_database(database_path=None):
    """Create the database file and all tables, dropping anything already there."""
    if database_path is None:
        database_path = config.DATABASE_PATH

    database_path.parent.mkdir(parents=True, exist_ok=True)

    connection = sqlite3.connect(database_path)
    connection.executescript(SCHEMA)
    connection.commit()
    return connection


def load_gates(connection):
    """Write the gate roster into the gates table."""
    roster = gates_module.build_gate_roster()

    rows = []
    for gate in roster:
        rows.append((gate.gate_id, gate.concourse, gate.size, gate.walk_cost))

    connection.executemany(
        "INSERT INTO gates (gate_id, concourse, size, walk_cost) VALUES (?, ?, ?, ?)",
        rows,
    )
    connection.commit()
    return len(rows)


def load_turns_and_blocks(connection, turns):
    """Write turns and their gate occupancy blocks into the database.

    turn_id is the DataFrame's row position, so block.turn_index lines up with
    turns.turn_id without any extra bookkeeping.
    """
    turns_to_write = turns.copy()
    turns_to_write["turn_id"] = range(len(turns_to_write))

    turns_to_write.to_sql("turns", connection, if_exists="append", index=False)

    blocks = build_turns.occupancy_intervals(turns)
    blocks = blocks.rename(columns={"turn_index": "turn_id"})
    # Each block inherits the calendar date of the turn it came from, so the
    # API can pull a day's worth of blocks with one indexed lookup.
    blocks["arrival_date"] = blocks["turn_id"].map(turns_to_write["arrival_date"])
    blocks.to_sql("gate_blocks", connection, if_exists="append", index=False)

    connection.commit()
    return len(turns_to_write), len(blocks)


def record_build_facts(connection, facts):
    """Store how this database was built, so results are reproducible.

    Anyone looking at a number the site produces can query this table and see
    the parameter values that produced it. That matters more than it sounds:
    the towing threshold alone changes peak gate demand by a factor of two.
    """
    rows = []
    for key in facts:
        rows.append((key, str(facts[key])))

    connection.executemany(
        "INSERT OR REPLACE INTO build_log (key, value) VALUES (?, ?)", rows
    )
    connection.commit()


def main():
    """Build the whole database from the filtered BTS file."""
    print("Loading flights...")
    flights = build_turns.load_flights()
    print("  usable flight records:", len(flights))

    print("Building arrival and departure events...")
    arrivals = build_turns.build_arrival_events(flights)
    departures = build_turns.build_departure_events(flights)
    print("  arrivals at SEA:", len(arrivals))
    print("  departures from SEA:", len(departures))

    print("Pairing turns...")
    turns, report = build_turns.pair_turns(arrivals, departures)
    print("  turns built:", report["turns_built"])
    print("  dropped, gap too short:", report["dropped_too_short"])
    print("  dropped, gap too long:", report["dropped_too_long"])
    print("  dropped, no matching departure:", report["dropped_no_departure"])

    print("Creating database at", config.DATABASE_PATH)
    connection = create_database()

    gate_count = load_gates(connection)
    turn_count, block_count = load_turns_and_blocks(connection, turns)
    print("  gates:", gate_count)
    print("  turns:", turn_count)
    print("  gate blocks:", block_count)

    record_build_facts(connection, {
        "source_file": config.FILTERED_FLIGHTS_CSV.name,
        "year": config.YEAR,
        "carrier": config.CARRIER,
        "airport": config.AIRPORT,
        "min_turn_minutes": config.MIN_TURN_MINUTES,
        "max_turn_minutes": config.MAX_TURN_MINUTES,
        "towing_rule": "Port of Seattle maximum gate occupancy",
        "max_gate_occupancy_minutes": config.MAX_GATE_OCCUPANCY_MINUTES,
        "preferential_gates": config.PREFERENTIAL_GATE_COUNT,
        "common_use_gates": config.COMMON_USE_GATE_COUNT,
        "arrival_gate_minutes": config.ARRIVAL_GATE_MINUTES,
        "departure_gate_minutes": config.DEPARTURE_GATE_MINUTES,
        "turns_built": report["turns_built"],
        "dropped_too_long": report["dropped_too_long"],
        "dropped_no_departure": report["dropped_no_departure"],
    })

    connection.close()
    print("Done.")


if __name__ == "__main__":
    main()
